base_url = "https://gwangjinkim.github.io/your-repo-name/"
title = "My GPT Blog Empire"
description = "A lean, static, GPT-powered blog built with Zola and Cloudflare Workers."
theme = "even"
output_dir = "docs"

compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true
default_language = "en"

taxonomies = [
  { name = "tags", rss = true },
  { name = "categories" }
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author = "Gwang-Jin Kim"
copyright = "© 2025 Gwang-Jin Kim"
google_analytics = ""
